### ISSUE TITLE
Device tracker crashes if no position found for vehicle

### ISSUE THREAD

**Issue by filcole** [filcole/home-assistant#7]
2019-01-05 18:13:38 INFO (MainThread) [homeassistant.components.nissan_leaf] Latest server date=05-Jan-2019 18:13
2019-01-05 18:13:38 INFO (MainThread) [homeassistant.components.nissan_leaf] Using updated server info instead of waiting for request_updated
2019-01-05 18:13:38 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Server Response:
2019-01-05 18:13:38 DEBUG (MainThread) [homeassistant.components.nissan_leaf] {'cruising_range_ac_on_km': 155.0, 'battery_remaining_amount': '220', 'is_quick_charging': False, 'is_connected_to_q, 'cruising_range_ac_off_km': 179.0, 'charging_status': 'NOT_CHARGING', 'answer': {'BatteryStatusRecords': {'OperationDateAndTime': '05-Jan-2019 18:13', 'PluginState': 'NOT_CONNECTED', 'BatterySmainingAmountWH': '24720', 'BatteryCapacity': '240', 'BatteryRemainingAmountkWH': '', 'BatteryChargingStatus': 'NOT_CHARGING', 'BatteryRemainingAmount': '220'}, 'CruisingRangeAcOff': '179000', ' '2019/01/05 18:13', 'TimeRequiredToFull200': {'HourRequiredToFull': '3', 'MinutesRequiredToFull': '0'}, 'NotificationDateAndTime': '2019/01/05 18:13', 'OperationResult': 'START', 'TimeRequiredT'MinutesRequiredToFull': '30'}, 'TimeRequiredToFull': {'HourRequiredToFull': '4', 'MinutesRequiredToFull': '0'}}, 'status': 200}, 'battery_capacity': '240', 'is_charging': False, 'state_of_charg667, 'time_to_full_l2_6kw': datetime.timedelta(0, 5400), 'plugin_state': 'NOT_CONNECTED', 'time_to_full_l2': datetime.timedelta(0, 10800), 'time_to_full_trickle': datetime.timedelta(0, 14400)}
2019-01-05 18:13:38 DEBUG (Thread-8) [homeassistant.components.device_tracker.nissan_leaf] Updating device_tracker for Leaf1filc with position <pycarwings2.responses.CarwingsMyCarFinderResponse
2019-01-05 18:13:42 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Got climate data for Leaf.
2019-01-05 18:13:42 DEBUG (MainThread) [homeassistant.components.nissan_leaf] {'is_hvac_running': False}
2019-01-05 18:13:46 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (1). Waiting 5 seconds
2019-01-05 18:13:52 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (2). Waiting 5 seconds
2019-01-05 18:13:58 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (3). Waiting 5 seconds
2019-01-05 18:14:05 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (4). Waiting 5 seconds
2019-01-05 18:14:12 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (5). Waiting 5 seconds
2019-01-05 18:14:19 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (6). Waiting 5 seconds
2019-01-05 18:14:25 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (7). Waiting 5 seconds
2019-01-05 18:14:45 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (8). Waiting 5 seconds
2019-01-05 18:14:51 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (9). Waiting 5 seconds
2019-01-05 18:14:58 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (10). Waiting 5 seconds
2019-01-05 18:15:05 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (11). Waiting 5 seconds
2019-01-05 18:15:11 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (12). Waiting 5 seconds
2019-01-05 18:15:30 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (13). Waiting 5 seconds
2019-01-05 18:15:37 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (14). Waiting 5 seconds
2019-01-05 18:15:56 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (15). Waiting 5 seconds
2019-01-05 18:16:02 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (16). Waiting 5 seconds
2019-01-05 18:16:22 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (17). Waiting 5 seconds
2019-01-05 18:16:28 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (18). Waiting 5 seconds
2019-01-05 18:16:34 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (19). Waiting 5 seconds
2019-01-05 18:16:41 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (20). Waiting 5 seconds
2019-01-05 18:16:48 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Location data not in yet. (SJNFAAZE0U6038107) (21). Waiting 5 seconds
2019-01-05 18:16:54 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Empty Location Response Received
2019-01-05 18:16:54 DEBUG (Thread-4) [homeassistant.components.device_tracker.nissan_leaf] Updating device_tracker for Leaf1filc with position <pycarwings2.responses.CarwingsMyCarFinderResponse
2019-01-05 18:16:54 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Could use base interval=1:00:00
2019-01-05 18:16:54 DEBUG (Thread-3) [homeassistant.components.device_tracker.nissan_leaf] No position found for vehicle SJNFAAZE0U6038107
2019-01-05 18:16:54 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Resulting interval=1:00:00
2019-01-05 18:16:54 DEBUG (MainThread) [homeassistant.components.nissan_leaf] Next interval=2019-01-05 19:16:54.726266+00:00
2019-01-05 18:24:14 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/phil/repos/home-assistant/homeassistant/components/device_tracker/nissan_leaf.py", line 38, in see_vehicle
    value.data[DATA_LOCATION].latitude,
AttributeError: 'NoneType' object has no attribute 'latitude'

**Comment by filcole** [comment]
The check on an empty response was incorrect. This should be fixed by commit https://github.com/filcole/home-assistant/commit/c19a36298f4dd31403af85c0d7fdd6cb4ad7682a
